#pragma once

#include <Core/Base/BitFlags.h>
#include <Core/Base/CString.h>
#include <Core/Base/Hash/FastCRC32.h>
#include <Core/Base/Hash/FNV1A.h>
#include <Core/Base/HashMap.h>
#include <Core/Base/Map.h>
#include <Core/Base/NameOf.h>
#include <Core/Base/Optional.h>
#include <Core/Base/Path.h>
#include <Core/Base/RefCountPtr.h>
#include <Core/Base/String.h>
#include <Core/Base/StringID.h>
#include <Core/Base/StringView.h>
#include <Core/Base/TypeTraits.h>
#include <Core/Base/Vector.h>
#include <Core/Modules/IModule.h>
#include <Core/Modules/ModuleManager.h>
#include <Core/Misc/CommandLine.h>
#include <Core/HAL/PlatformApplication.h>
#include <Core/HAL/PlatformEvent.h>
#include <Core/HAL/PlatformModule.h>
#include <Core/HAL/PlatformProcess.h>
#include <Core/HAL/PlatformWindow.h>
#include <Core/HAL/PlatformTime.h>
#include <Core/HAL/PlatformTypes.h>